send_start: True
send_end: False

twitter:
  consumer_key:
  consumer_secret:
  access_token_key:
  access_token_secret:

mastodon:
  api_base_url:
  client_key:
  client_secret:
  access_token:

twitch:
  client_id:
  oauth_token:

tweet_format:
  stream_start:
    - "[{time}] {display_name} is now streaming {game}! https://twitch.tv/{name}"
    - "[{time}] {display_name} is now playing {game}! https://twitch.tv/{name}"
    - "[{time}] {display_name} is now streaming {game} on #twitch https://twitch.tv/{name}"
    - "[{time}] {display_name} is currently streaming {game}! https://twitch.tv/{name}"
    - "[{time}] {display_name} is now playing {game}! https://twitch.tv/{name}"
  stream_end:
    - "[{time}] {display_name}'s stream is now over. Thanks for watching!"
    - "[{time}] {display_name}'s stream has ended."
    - "[{time}] {display_name} is now offline. Thanks for watching!"

polling_interval: 180

logging:
  version: 1
  formatters:
    brief:
      format: '%(message)s'
    precise:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: brief
      level: ERROR
      stream: ext://sys.stdout
    file:
      class : logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: precise
      interval: 1
      when: D
      backupCount: 7
      filename: dopefish_mastodon.log
  root:
      level: INFO
      handlers:
        - file
        - console
      propagate: True
